In [1]:
%matplotlib inline        

In [2]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import scale

In [3]:
data_sns=pd.read_csv('snsdata.csv')

In [4]:
data_sns.head()

gradyear gender     age  friends  basketball  football  soccer  softball  \
0      2006      M  18.982        7           0         0       0         0   
1      2006      F  18.801        0           0         1       0         0   
2      2006      M  18.335       69           0         1       0         0   
3      2006      F  18.875        0           0         0       0         0   
4      2006    NaN  18.995       10           0         0       0         0   

   volleyball  swimming  ...    blonde  mall  shopping  clothes  hollister  \
0           0         0  ...         0     0         0        0          0   
1           0         0  ...         0     1         0        0          0   
2           0         0  ...         0     0         0        0          0   
3           0         0  ...         0     0         0        0          0   
4           0         0  ...         0     0         2        0          0   

   abercrombie  die  death  drunk  drugs  
0            0    0      0      0      0  
1            0    0      0      0      0  
2            0    0      1      0      0  
3            0    0      0      0      0  
4            0    0      0      1      1  

[5 rows x 40 columns]

In [5]:
[(col, type(data_sns[col][0])) for col in data_sns.columns] 

[('gradyear', numpy.int64),
 ('gender', str),
 ('age', numpy.float64),
 ('friends', numpy.int64),
 ('basketball', numpy.int64),
 ('football', numpy.int64),
 ('soccer', numpy.int64),
 ('softball', numpy.int64),
 ('volleyball', numpy.int64),
 ('swimming', numpy.int64),
 ('cheerleading', numpy.int64),
 ('baseball', numpy.int64),
 ('tennis', numpy.int64),
 ('sports', numpy.int64),
 ('cute', numpy.int64),
 ('sex', numpy.int64),
 ('sexy', numpy.int64),
 ('hot', numpy.int64),
 ('kissed', numpy.int64),
 ('dance', numpy.int64),
 ('band', numpy.int64),
 ('marching', numpy.int64),
 ('music', numpy.int64),
 ('rock', numpy.int64),
 ('god', numpy.int64),
 ('church', numpy.int64),
 ('jesus', numpy.int64),
 ('bible', numpy.int64),
 ('hair', numpy.int64),
 ('dress', numpy.int64),
 ('blonde', numpy.int64),
 ('mall', numpy.int64),
 ('shopping', numpy.int64),
 ('clothes', numpy.int64),
 ('hollister', numpy.int64),
 ('abercrombie', numpy.int64),
 ('die', numpy.int64),
 ('death', numpy.int64),
 ('drunk', nu

In [6]:
data_sns_num=data_sns.iloc[:,3:40]
data_sns_num.head()

friends  basketball  football  soccer  softball  volleyball  swimming  \
0        7           0         0       0         0           0         0   
1        0           0         1       0         0           0         0   
2       69           0         1       0         0           0         0   
3        0           0         0       0         0           0         0   
4       10           0         0       0         0           0         0   

   cheerleading  baseball  tennis  ...    blonde  mall  shopping  clothes  \
0             0         0       0  ...         0     0         0        0   
1             0         0       0  ...         0     1         0        0   
2             0         0       0  ...         0     0         0        0   
3             0         0       0  ...         0     0         0        0   
4             0         0       0  ...         0     0         2        0   

   hollister  abercrombie  die  death  drunk  drugs  
0          0            0    0      0      0      0  
1          0            0    0      0      0      0  
2          0            0    0      1      0      0  
3          0            0    0      0      0      0  
4          0            0    0      0      1      1  

[5 rows x 37 columns]

In [7]:
matrix_correlations=data_sns_num.corr()
matrix_correlations

friends  basketball  football    soccer  softball  volleyball  \
friends       1.000000    0.053052  0.031738  0.027402  0.055935    0.046853   
basketball    0.053052    1.000000  0.177333  0.071375  0.123884    0.136199   
football      0.031738    0.177333  1.000000  0.063986  0.046312    0.058534   
soccer        0.027402    0.071375  0.063986  1.000000  0.012366    0.029045   
softball      0.055935    0.123884  0.046312  0.012366  1.000000    0.115052   
volleyball    0.046853    0.136199  0.058534  0.029045  0.115052    1.000000   
swimming      0.029147    0.025810  0.035534  0.039001  0.020749    0.043515   
cheerleading  0.054851    0.041059  0.088658  0.014794  0.026927    0.023508   
baseball      0.027419    0.125802  0.183679  0.033696  0.052131    0.024702   
tennis        0.008818    0.036987  0.031902  0.028848 -0.001948    0.025492   
sports        0.014868    0.165710  0.154553  0.089538  0.114614    0.090338   
cute          0.069577    0.040813  0.069626  0.033346  0.027047    0.039248   
sex           0.000374    0.043604  0.056704  0.014025  0.028452    0.013855   
sexy          0.031890    0.030631  0.029369  0.015299  0.006753    0.012099   
hot           0.044193    0.035072  0.046827  0.032686  0.023961    0.034395   
kissed        0.018776    0.064847  0.065681  0.027208  0.031933    0.023917   
dance         0.051955    0.053738  0.059671  0.010523  0.016548    0.023224   
band          0.015396    0.010042  0.043142  0.004735  0.010518   -0.008170   
marching      0.013910   -0.004417  0.016741 -0.007511  0.005440   -0.010947   
music         0.028792    0.059028  0.066126  0.029863  0.026298    0.017250   
rock          0.020261    0.084040  0.090284  0.050642  0.024287    0.022208   
god           0.046406    0.027179  0.032514  0.002689  0.018848    0.015318   
church        0.056025    0.056308  0.047236  0.028171  0.036681    0.027691   
jesus         0.029807    0.011552  0.013142  0.007313  0.008603    0.005712   
bible         0.011099    0.019818  0.006588  0.005581  0.001725    0.007737   
hair          0.033285    0.098283  0.104103  0.049187  0.048492    0.042390   
dress         0.040673    0.032171  0.043543  0.009979  0.023098    0.019762   
blonde        0.008502    0.018204  0.033070  0.015134  0.006857    0.008077   
mall          0.066716    0.069477  0.065207  0.022723  0.034093    0.035103   
shopping      0.084627    0.073422  0.056572  0.054580  0.050446    0.077030   
clothes       0.026906    0.076253  0.070793  0.022189  0.047182    0.030456   
hollister     0.056240    0.036633  0.063667  0.029353  0.024057    0.041156   
abercrombie   0.057502    0.033880  0.041708  0.022757  0.020079    0.043096   
die           0.010432    0.020331  0.023424  0.008942  0.012750    0.003543   
death         0.026358    0.017815  0.018757  0.004957  0.021312    0.014249   
drunk         0.017036    0.021744  0.038740  0.009390  0.008083    0.004995   
drugs        -0.006960    0.031330  0.031675  0.014844  0.015096    0.014548   

              swimming  cheerleading  baseball    tennis    ...       blonde  \
friends       0.029147      0.054851  0.027419  0.008818    ...     0.008502   
basketball    0.025810      0.041059  0.125802  0.036987    ...     0.018204   
football      0.035534      0.088658  0.183679  0.031902    ...     0.033070   
soccer        0.039001      0.014794  0.033696  0.028848    ...     0.015134   
softball      0.020749      0.026927  0.052131 -0.001948    ...     0.006857   
volleyball    0.043515      0.023508  0.024702  0.025492    ...     0.008077   
swimming      1.000000      0.023826  0.027672  0.031290    ...     0.021183   
cheerleading  0.023826      1.000000  0.032835  0.000579    ...     0.020405   
baseball      0.027672      0.032835  1.000000  0.007919    ...     0.020282   
tennis        0.031290      0.000579  0.007919  1.000000    ...     0.006102   
sports        0.043068      0.022184  0.132156  0.052328    ...     0.013902   
cute          

In [8]:
type(matrix_correlations)

pandas.core.frame.DataFrame

In [9]:
matrix_correlations.to_csv('matrix_correlations.csv')

In [10]:
data_sns_scale=scale(data_sns_num, axis=0, with_mean=True, with_std=True, copy=True)
data_sns_scale

array([[-0.63452768, -0.33221726, -0.35769737, ..., -0.26153016,
        -0.22040264, -0.1749076 ],
       [-0.8261496 , -0.33221726,  1.06004883, ..., -0.26153016,
        -0.22040264, -0.1749076 ],
       [ 1.06269499, -0.33221726,  1.06004883, ...,  2.02790809,
        -0.22040264, -0.1749076 ],
       ..., 
       [-0.8261496 , -0.33221726,  1.06004883, ..., -0.26153016,
        -0.22040264, -0.1749076 ],
       [-0.8261496 , -0.33221726, -0.35769737, ..., -0.26153016,
        -0.22040264, -0.1749076 ],
       [-0.74402592,  2.15319868, -0.35769737, ..., -0.26153016,
        -0.22040264, -0.1749076 ]])

In [11]:
data_sns_scale.shape

(30000, 37)

In [12]:
data_sns_num['friends'].mean()

30.179466666666666

In [13]:
data_sns_num['friends'].std()

36.530877467552315

In [14]:
(data_sns_num.iloc[0,0] - data_sns_num['friends'].mean())/(data_sns_num['friends'].std())

-0.63451710644660198

In [15]:
(data_sns_num.iloc[2,0] - data_sns_num['friends'].mean())/(data_sns_num['friends'].std())

1.0626772753491822

In [16]:
from scipy.spatial.distance import cdist, pdist
from matplotlib import pyplot as plt
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

In [17]:
# Determine your k range
k_range = range(1,50)

# Fit the kmeans model for each n_clusters = k
k_means_var = [KMeans(n_clusters=k).fit(data_sns_scale) for k in k_range]
k_means_var

[KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
     n_clusters=1, n_init=10, n_jobs=1, precompute_distances='auto',
     random_state=None, tol=0.0001, verbose=0),
 KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
     n_clusters=2, n_init=10, n_jobs=1, precompute_distances='auto',
     random_state=None, tol=0.0001, verbose=0),
 KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
     n_clusters=3, n_init=10, n_jobs=1, precompute_distances='auto',
     random_state=None, tol=0.0001, verbose=0),
 KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
     n_clusters=4, n_init=10, n_jobs=1, precompute_distances='auto',
     random_state=None, tol=0.0001, verbose=0),
 KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
     n_clusters=5, n_init=10, n_jobs=1, precompute_distances='auto',
     random_state=None, tol=0.0001, verbose=0),
 KMeans(algorithm='auto', copy_x=True, init='k-means++', max

In [18]:
# Pull out the cluster centers for each model
centroids = [X.cluster_centers_ for X in k_means_var]
centroids

[array([[  2.18183249e-15,   2.70954666e-14,  -2.74506344e-16,
           1.00454885e-14,   4.12125149e-15,   1.40255677e-14,
           1.56938536e-15,  -1.37784228e-16,  -2.78770895e-15,
           8.51585469e-16,  -3.93046706e-15,   8.37565202e-15,
           7.80936427e-16,   5.21966544e-15,  -1.85072587e-14,
          -4.42934763e-15,  -1.85168325e-14,  -3.78482431e-16,
          -4.29323244e-15,  -2.99095563e-15,   3.49842562e-15,
           1.80540027e-15,   1.98022709e-15,   1.89442536e-15,
           3.64786904e-16,   1.59509813e-15,   9.78330935e-15,
          -9.81861814e-16,  -2.11316631e-14,  -1.18263658e-14,
          -1.43128657e-14,  -3.38804595e-14,  -1.67646471e-14,
          -3.54040501e-15,  -3.36445686e-16,   1.24659172e-15,
          -1.06786432e-15]]),
 array([[-0.04245074, -0.08310743, -0.07448875, -0.03703988, -0.0427967 ,
         -0.0496969 , -0.0524934 , -0.06108651, -0.04366712, -0.02321688,
         -0.0765829 , -0.12193181, -0.09960374, -0.06645324, -0.08

In [19]:
centroids[0]

array([[  2.18183249e-15,   2.70954666e-14,  -2.74506344e-16,
          1.00454885e-14,   4.12125149e-15,   1.40255677e-14,
          1.56938536e-15,  -1.37784228e-16,  -2.78770895e-15,
          8.51585469e-16,  -3.93046706e-15,   8.37565202e-15,
          7.80936427e-16,   5.21966544e-15,  -1.85072587e-14,
         -4.42934763e-15,  -1.85168325e-14,  -3.78482431e-16,
         -4.29323244e-15,  -2.99095563e-15,   3.49842562e-15,
          1.80540027e-15,   1.98022709e-15,   1.89442536e-15,
          3.64786904e-16,   1.59509813e-15,   9.78330935e-15,
         -9.81861814e-16,  -2.11316631e-14,  -1.18263658e-14,
         -1.43128657e-14,  -3.38804595e-14,  -1.67646471e-14,
         -3.54040501e-15,  -3.36445686e-16,   1.24659172e-15,
         -1.06786432e-15]])

In [20]:
centroids[1]

array([[-0.04245074, -0.08310743, -0.07448875, -0.03703988, -0.0427967 ,
        -0.0496969 , -0.0524934 , -0.06108651, -0.04366712, -0.02321688,
        -0.0765829 , -0.12193181, -0.09960374, -0.06645324, -0.08063653,
        -0.13893893, -0.09509223, -0.05411946, -0.01831989, -0.10738674,
        -0.10201684, -0.06882127, -0.07941378, -0.04123499, -0.0366462 ,
        -0.1906143 , -0.09687957, -0.02573833, -0.12813582, -0.12611557,
        -0.15620489, -0.11554336, -0.11871314, -0.09710136, -0.07495771,
        -0.09428172, -0.11670012],
       [ 0.26120262,  0.51136633,  0.4583349 ,  0.22790917,  0.26333135,
         0.30578882,  0.32299588,  0.37586992,  0.26868712,  0.1428552 ,
         0.47122036,  0.75025566,  0.61286935,  0.40889183,  0.49616269,
         0.8549018 ,  0.58510969,  0.33300111,  0.11272367,  0.66075876,
         0.62771734,  0.42346248,  0.488639  ,  0.25372201,  0.22548687,
         1.17286424,  0.59610736,  0.1583699 ,  0.7884294 ,  0.77599869,
         0.96114

In [21]:
centroids[2]

array([[  4.03217771e-01,   4.55743943e-01,   4.48664313e-01,
          2.69550943e-01,   3.41145599e-01,   3.79579366e-01,
          3.22156555e-01,   3.72803977e-01,   2.32657797e-01,
          1.56212067e-01,   2.65591697e-01,   5.80460132e-01,
         -9.56945131e-03,   2.27222827e-01,   4.30351007e-01,
         -4.66111992e-02,   4.64156538e-01,   1.29739487e-01,
          8.66140057e-02,   2.57633425e-01,   1.80684993e-01,
          3.09343037e-01,   4.91632540e-01,   2.37328642e-01,
          2.01508489e-01,   2.69840764e-01,   3.97666609e-01,
          3.84201941e-02,   5.64553989e-01,   7.81709553e-01,
          4.41667565e-01,   4.75273790e-01,   4.37808511e-01,
          4.13259989e-02,   1.24768812e-01,   1.65687565e-03,
         -6.55071452e-02],
       [ -5.82690986e-03,   3.69945500e-01,   3.89796237e-01,
          1.32681987e-01,   1.68162341e-01,   1.05890916e-01,
          2.70348505e-01,   2.16386597e-01,   2.85635453e-01,
          1.09834424e-01,   8.37034544e-01,

In [22]:
# Calculate the Euclidean distance from 
# each point to each cluster center
k_euclid = [cdist(data_sns_scale, cent, 'euclidean') for cent in centroids]
k_euclid[1]

array([[  1.46532946,   5.02382902],
       [ 10.83528775,  10.04918296],
       [  3.26158024,   5.22420175],
       ..., 
       [  2.53253626,   5.29940943],
       [  1.8463359 ,   5.07554556],
       [  3.05275089,   5.2355929 ]])

In [23]:
dist = [np.min(ke,axis=1) for ke in k_euclid]
dist[1]

array([  1.46532946,  10.04918296,   3.26158024, ...,   2.53253626,
         1.8463359 ,   3.05275089])

In [24]:
# Total within-cluster sum of squares
wcss = [sum(d**2) for d in dist]
wcss

[1109999.9999999939,
 1053482.1591936392,
 1023421.4503174213,
 994339.50269560516,
 975620.96279582125,
 954093.74040279817,
 928251.04692963581,
 906754.70010449656,
 887911.64008607832,
 868491.87820186,
 856430.46465775126,
 838762.62345778279,
 825729.05181392643,
 812501.16661352816,
 804319.70127601828,
 787057.72748920822,
 774246.66139594186,
 763602.11710713524,
 749406.27937774535,
 740812.95615354518,
 728683.03728065046,
 716088.2939185563,
 707329.91120748862,
 697083.46553695865,
 690028.71387902938,
 677239.94840678887,
 672794.62580794864,
 662530.12654865545,
 653058.54360466392,
 644408.23116964637,
 641776.45051732799,
 633805.52287382993,
 628707.03537355282,
 619790.10861622973,
 614028.97875682381,
 608095.26413224509,
 607127.12472411047,
 601863.390055859,
 590525.104934128,
 587859.68015732674,
 579918.7690204574,
 577809.63660992763,
 575561.84704670031,
 574566.51508335292,
 571773.27311763621,
 567704.46518229006,
 562287.31529975566,
 556805.20652085473,
 

In [25]:
# The total sum of squares
tss = sum(pdist(data_sns_scale)**2)/(data_sns_scale.shape[0])
tss

MemoryError: 

In [ ]:
# The between-cluster sum of squares
bss = tss - wcss
bss

In [ ]:
# elbow curve
%matplotlib inline
fig = plt.figure()
ax = fig.add_subplot(111)
ax.plot(k_range, bss/tss*100, 'g*-')
ax.set_ylim((0,100))
plt.grid(True)
plt.xlabel('Nro. clusters')
plt.ylabel('% variance explained')
plt.title('Variance Explained vs. k')

In [ ]:
avgWithinSumSquare = [sum(d)/data_sns_scale.shape[0] for d in dist]
avgWithinSumSquare

In [ ]:
# plot elbow curve
fig = plt.figure()
ax = fig.add_subplot(111)
ax.plot(avgWithinSumSquare, 'b*-')
plt.grid(True)
plt.xlabel('No. of clusters')
plt.ylabel('Avg sum of squares')
tt = plt.title('Elbow Curve')

In [ ]:
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
import numpy as np
from sklearn.decomposition import PCA

In [ ]:
data_sns_num.head()

In [ ]:
pc_toarray=data_sns_num.values

In [ ]:
hpc = PCA(n_components=2).fit(pc_toarray)
hpc

In [ ]:
x=hpc.explained_variance_ratio_
x.sum()

In [ ]:
print(hpc.explained_variance_ratio_) 

In [ ]:
hpc = PCA(n_components=2).fit_transform(pc_toarray)
hpc

In [ ]:
# Determine your k range
k_range = range(1,40)

# Fit the kmeans model for each n_clusters = k
k_means_var = [KMeans(n_clusters=k).fit(hpc) for k in k_range]
k_means_var

In [ ]:
# Pull out the cluster centers for each model
centroids = [X.cluster_centers_ for X in k_means_var]
centroids

In [ ]:
# Calculate the Euclidean distance from 
# each point to each cluster center
k_euclid = [cdist(hpc, cent, 'euclidean') for cent in centroids]
k_euclid[1]

In [ ]:
dist = [np.min(ke,axis=1) for ke in k_euclid]
dist[1]

In [ ]:
avgWithinSumSquare = [sum(d)/hpc.shape[0] for d in dist]
avgWithinSumSquare

In [ ]:
# plot elbow curve
fig = plt.figure()
ax = fig.add_subplot(111)
ax.plot(avgWithinSumSquare, 'b*-')
plt.grid(True)
plt.xlabel('No. of clusters')
plt.ylabel('Avg sum of squares')
tt = plt.title('Elbow Curve')

In [ ]:
km = KMeans(15, init='k-means++', random_state = 3425) # initialize
km.fit(hpc)

In [ ]:
data_sns['pref_cluster'] = km.predict(hpc)
data_sns.head()

In [ ]:
data_sns.groupby('pref_cluster').gradyear.count()

In [ ]:
km = KMeans(15, init='k-means++', random_state = 1) # initialize
km.fit(hpc)
data_sns['pref_cluster2'] = km.predict(hpc)
data_sns.head()

In [105]:
data_sns.groupby('pref_cluster2').gradyear.count()

pref_cluster2
0     8593
1     2393
2      347
3     3211
4     1849
5       56
6     4680
7        2
8     1073
9      147
10       5
11    3959
12    3043
13       1
14     641
Name: gradyear, dtype: int64

In [ ]:
from sklearn.metrics import silhouette_score

labels = km.labels_
metrics.silhouette_score(hpc, labels, metric='euclidean')

In [ ]:
labels = km.labels_
metrics.silhouette_score(X, labels, metric='euclidean')
...                                                      
0.55...

