# Sesión 2. Inferencia Estadística

# Distribuciones de probabilidad para una variable aleatoria discreta

In [147]:
# Importar la librería NumPy
import numpy as np

In [148]:
# Importar la librería Pandas desde Python.
import pandas as pd

In [149]:
# Importar datos en formato xls.
data_hipotecas = pd.read_excel('C:/Users/AMD/Documents/Python_Analytcis/hipotecas.xlsx')

In [150]:
data_hipotecas.head()

Tienda  Número de Hipotecas aprobadas por semana
0       5                                         2
1       5                                         6
2       2                                         4
3       2                                         6
4       2                                         2

In [151]:
data_hipotecas[data_hipotecas['Tienda']==1].groupby(['Tienda','Número de Hipotecas aprobadas por semana'])['Tienda'].count()

Tienda  Número de Hipotecas aprobadas por semana
1       0                                           239
        1                                           208
        2                                           194
        3                                           215
        4                                           224
        5                                           219
        6                                           242
        7                                           210
        8                                           221
Name: Tienda, dtype: int64

In [152]:
#data_hipotecas['Tienda'].groupby(data_hipotecas['Tienda']).count()
data_t1=pd.DataFrame(data_hipotecas[data_hipotecas['Tienda']==1].groupby(['Tienda','Número de Hipotecas aprobadas por semana'])['Tienda'].count())
data_t1

Tienda
Tienda Número de Hipotecas aprobadas por semana        
1      0                                            239
       1                                            208
       2                                            194
       3                                            215
       4                                            224
       5                                            219
       6                                            242
       7                                            210
       8                                            221

In [153]:
data_t1_0=pd.DataFrame(data_hipotecas[data_hipotecas['Tienda']==1].groupby(['Tienda'])['Tienda'].count())
data_t1_0

Tienda
Tienda        
1         1972

In [154]:
data_hipotecas[data_hipotecas['Tienda']==1].groupby(['Tienda','Número de Hipotecas aprobadas por semana'])['Tienda'].count()/data_hipotecas[data_hipotecas['Tienda']==1].groupby(['Tienda'])['Tienda'].count()

Tienda  Número de Hipotecas aprobadas por semana
1       0                                           0.121197
        1                                           0.105477
        2                                           0.098377
        3                                           0.109026
        4                                           0.113590
        5                                           0.111055
        6                                           0.122718
        7                                           0.106491
        8                                           0.112069
Name: Tienda, dtype: float64

In [155]:
def generateNumber(num):
    mylist = []
    for i in range(num+1):
         mylist.append(i)
    return mylist


x = generateNumber(8)
x

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [156]:
a=data_hipotecas[data_hipotecas['Tienda']==1].groupby(['Tienda','Número de Hipotecas aprobadas por semana'])['Tienda'].count()/data_hipotecas[data_hipotecas['Tienda']==1].groupby(['Tienda'])['Tienda'].count()*x

In [157]:
a

Tienda  Número de Hipotecas aprobadas por semana
1       0                                           0.000000
        1                                           0.105477
        2                                           0.196755
        3                                           0.327079
        4                                           0.454361
        5                                           0.555274
        6                                           0.736308
        7                                           0.745436
        8                                           0.896552
Name: Tienda, dtype: float64

In [158]:
ex=a.sum()
ex

4.017241379310345

In [159]:
b=np.array(x)
c=b**2
c

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64])

In [160]:
d=data_hipotecas[data_hipotecas['Tienda']==1].groupby(['Tienda','Número de Hipotecas aprobadas por semana'])['Tienda'].count()/data_hipotecas[data_hipotecas['Tienda']==1].groupby(['Tienda'])['Tienda'].count()*c

In [161]:
d

Tienda  Número de Hipotecas aprobadas por semana
1       0                                           0.000000
        1                                           0.105477
        2                                           0.393509
        3                                           0.981237
        4                                           1.817444
        5                                           2.776369
        6                                           4.417850
        7                                           5.218053
        8                                           7.172414
Name: Tienda, dtype: float64

In [162]:
ex2=d.sum()
ex2

22.88235294117647

In [163]:
vx=ex2-(ex**2)
vx

6.744124641533187

# Distribución Binomial

In [164]:
from scipy.stats import binom
import matplotlib.pyplot as plt

In [165]:
x=3
n=10
p=0.5
prob = binom.cdf(x, n, p)
prob

0.17187499999999994

In [166]:
pd=1-prob
pd

0.828125

# Distribución Poisson

In [167]:
# Importar datos en formato xls.
import pandas as pd
autos_averias = pd.read_excel('C:/Users/AMD/Documents/Python_Analytcis/averias_autos.xlsx')

In [168]:
autos_averias.head()

Marca  nro_averias
0  Dodge            3
1   Ford            3
2   Ford            2
3  Dodge            1
4  Dodge            2

In [169]:
lambda1=autos_averias[autos_averias['Marca']=='Dodge'].groupby(['Marca'])['nro_averias'].mean()
lambda1

Marca
Dodge    1.967645
Name: nro_averias, dtype: float64

In [170]:
lambda2=autos_averias[autos_averias['Marca']=='Ford'].groupby(['Marca'])['nro_averias'].mean()
lambda2

Marca
Ford    2.020821
Name: nro_averias, dtype: float64

In [171]:
from scipy.stats import poisson
import matplotlib.pyplot as plt

In [172]:
x=0
mu=lambda1
prob1 = poisson.cdf(x, mu)
prob1

array([ 0.13978562])

In [173]:
x=0
mu=lambda2
prob2 = poisson.cdf(x, mu)
prob2

array([ 0.13254658])

# Estandarización de los datos

In [174]:
# Importar datos en formato xls.
import pandas as pd
churners_data = pd.read_excel('C:/Users/AMD/Documents/Python_Analytcis/Churners.xlsx')

In [175]:
churners_data.head()

ID  EDAD       SEXO    CIVIL  HIJOS  INGRESO                    AUTO  \
0   0    57   Femenino   Casado      2  27535.3     Es dueño de un auto   
1   4    68   Femenino   Casado      2  81000.9  No es dueño de un auto   
2   8    34  Masculino  Soltero      0  87467.1     Es dueño de un auto   
3  10    60  Masculino   Casado      2  83220.6  No es dueño de un auto   
4  13    28   Femenino   Casado      2  20850.4  No es dueño de un auto   

        CHURN  
0  Voluntario  
1  Voluntario  
2      Actual  
3  Voluntario  
4  Voluntario

In [176]:
churners_data_0=churners_data[churners_data['CHURN']=='Voluntario']

In [177]:
churners_data_0.head()

ID  EDAD       SEXO    CIVIL  HIJOS   INGRESO                    AUTO  \
0   0    57   Femenino   Casado      2  27535.30     Es dueño de un auto   
1   4    68   Femenino   Casado      2  81000.90  No es dueño de un auto   
3  10    60  Masculino   Casado      2  83220.60  No es dueño de un auto   
4  13    28   Femenino   Casado      2  20850.40  No es dueño de un auto   
6  19    87   Femenino  Soltero      2   3776.12  No es dueño de un auto   

        CHURN  
0  Voluntario  
1  Voluntario  
3  Voluntario  
4  Voluntario  
6  Voluntario

In [178]:
churners_ing=churners_data_0['INGRESO']

In [179]:
churners_ing.head()

0    27535.30
1    81000.90
3    83220.60
4    20850.40
6     3776.12
Name: INGRESO, dtype: float64

In [180]:
import numpy as np

In [181]:
from scipy import stats

In [182]:
score_churners = stats.zscore(churners_ing) # estandarizamos los datos

In [183]:
pd.DataFrame(score_churners).head()

0
0 -0.728985
1  1.142023
2  1.219701
3 -0.962921
4 -1.560429

In [184]:
churners_ing.head()

0    27535.30
1    81000.90
3    83220.60
4    20850.40
6     3776.12
Name: INGRESO, dtype: float64

In [185]:
pd.DataFrame(churners_ing).mean()

INGRESO    48366.650984
dtype: float64

In [186]:
pd.DataFrame(churners_ing).std()

INGRESO    28603.710304
dtype: float64

In [187]:
pd.DataFrame(score_churners).std()

0    1.000976
dtype: float64

In [188]:
pd.DataFrame(score_churners).std()

0    1.000976
dtype: float64

In [189]:
z=(50000-churners_ing.mean())/churners_ing.std()
z

0.05710269745536449

In [190]:
prob = 1 - stats.norm.cdf(z)
prob

0.47723169383645603

In [191]:
churners_data_1=churners_data[churners_data['CHURN']=='Actual']
churners_data_1.head()

ID  EDAD       SEXO    CIVIL  HIJOS  INGRESO                    AUTO  \
2    8    34  Masculino  Soltero      0  87467.1     Es dueño de un auto   
5   17    52  Masculino  Soltero      0  84112.6  No es dueño de un auto   
8   22    76  Masculino   Casado      2  30933.6     Es dueño de un auto   
11  28    90   Femenino   Casado      0  91620.6  No es dueño de un auto   
12  30    62  Masculino  Soltero      0  96501.9     Es dueño de un auto   

     CHURN  
2   Actual  
5   Actual  
8   Actual  
11  Actual  
12  Actual

In [192]:
nchurners_ing=churners_data_1['INGRESO']

In [193]:
score_nchurners = stats.zscore(nchurners_ing) # estandarizamos los datos

In [194]:
z=(50000-nchurners_ing.mean())/nchurners_ing.std()
z

-0.07263464252532714

In [195]:
prob = 1 - stats.norm.cdf(z)
prob

0.52895157061581521

# T test

In [196]:
from __future__ import print_function

import numpy as np
from scipy.stats import ttest_ind, ttest_ind_from_stats
from scipy.special import stdtr

In [197]:
churners_data = pd.read_excel('C:/Users/AMD/Documents/Python_Analytcis/Churners.xlsx')

In [198]:
churners_data.head()

ID  EDAD       SEXO    CIVIL  HIJOS  INGRESO                    AUTO  \
0   0    57   Femenino   Casado      2  27535.3     Es dueño de un auto   
1   4    68   Femenino   Casado      2  81000.9  No es dueño de un auto   
2   8    34  Masculino  Soltero      0  87467.1     Es dueño de un auto   
3  10    60  Masculino   Casado      2  83220.6  No es dueño de un auto   
4  13    28   Femenino   Casado      2  20850.4  No es dueño de un auto   

        CHURN  
0  Voluntario  
1  Voluntario  
2      Actual  
3  Voluntario  
4  Voluntario

In [199]:
churners_data_0=churners_data[churners_data['CHURN']=='Voluntario']

In [200]:
churners_edad=churners_data_0['EDAD']

In [201]:
churners_data_1=churners_data[churners_data['CHURN']=='Actual']

In [202]:
nchurners_edad=churners_data_1['EDAD']

In [203]:
# Use scipy.stats.ttest_ind.
t, p = ttest_ind(churners_edad, nchurners_edad, equal_var=False)
print("ttest_ind:            t = %g  p = %g" % (t, p))

ttest_ind:            t = 2.12927  p = 0.0334498


In [204]:
p_valor=(2-p)/2
p_valor

0.9832750870595256

In [205]:
churners_edad.mean()

59.113060428849906

In [206]:
nchurners_edad.mean()

56.42908653846154

In [207]:
import numpy as np
import scipy as sp
import scipy.stats

def mean_confidence_interval(data, confidence=0.95):
    a = 1.0*np.array(data)
    n = len(a)
    m, se = np.mean(a), scipy.stats.sem(a)
    h = se * sp.stats.t._ppf((1+confidence)/2., n-1)
    return m, m-h, m+h

# Intervalos de Confianza

In [208]:
churners_ing.head()

0    27535.30
1    81000.90
3    83220.60
4    20850.40
6     3776.12
Name: INGRESO, dtype: float64

In [209]:
import numpy as np
import scipy as sp
import scipy.stats

def mean_confidence_interval(data, confidence=0.95):
    a = 1.0*np.array(data)
    n = len(a)
    m, se = np.mean(a), scipy.stats.sem(a)
    h = se * sp.stats.t._ppf((1+confidence)/2., n-1)
    return m, m-h, m+h

In [210]:
mean_confidence_interval(churners_ing,0.95)

(48366.650984405453, 45885.577533845033, 50847.724434965872)

# Coeficiente de correlación

In [211]:
churners_data_0.head()

ID  EDAD       SEXO    CIVIL  HIJOS   INGRESO                    AUTO  \
0   0    57   Femenino   Casado      2  27535.30     Es dueño de un auto   
1   4    68   Femenino   Casado      2  81000.90  No es dueño de un auto   
3  10    60  Masculino   Casado      2  83220.60  No es dueño de un auto   
4  13    28   Femenino   Casado      2  20850.40  No es dueño de un auto   
6  19    87   Femenino  Soltero      2   3776.12  No es dueño de un auto   

        CHURN  
0  Voluntario  
1  Voluntario  
3  Voluntario  
4  Voluntario  
6  Voluntario

In [212]:
churners_eval=churners_data_0[['EDAD','INGRESO']]

In [213]:
churners_eval.head()

EDAD   INGRESO
0    57  27535.30
1    68  81000.90
3    60  83220.60
4    28  20850.40
6    87   3776.12

In [214]:
from scipy import stats

In [215]:
stats.pearsonr(churners_data_0['EDAD'], churners_data_0['INGRESO'])

(0.2063985658696835, 2.4257223178798058e-06)

In [216]:
stats.spearmanr(churners_data_0['EDAD'], churners_data_0['INGRESO'])

SpearmanrResult(correlation=0.1940862273596578, pvalue=9.5374822389871346e-06)

# Prueba de Independencia

In [71]:
churners_data_0.head()

ID  EDAD       SEXO    CIVIL  HIJOS   INGRESO                    AUTO  \
0   0    57   Femenino   Casado      2  27535.30     Es dueño de un auto   
1   4    68   Femenino   Casado      2  81000.90  No es dueño de un auto   
3  10    60  Masculino   Casado      2  83220.60  No es dueño de un auto   
4  13    28   Femenino   Casado      2  20850.40  No es dueño de un auto   
6  19    87   Femenino  Soltero      2   3776.12  No es dueño de un auto   

        CHURN  
0  Voluntario  
1  Voluntario  
3  Voluntario  
4  Voluntario  
6  Voluntario

In [89]:
churners_data_0.ix[3,2] # primero buscas el nombre del índice luego la posición

'Masculino'

In [86]:
churners_data_0.loc[3,'SEXO'] # solo busca nombre y columna

'Masculino'

In [90]:
churners_data_0.iloc[3,3] # busca por posición

'Casado'

In [217]:
a=churners_data['CHURN']
b=churners_data['SEXO']
churners = pd.DataFrame({"churn":a, 
                       "sexo":b})


voter_tab = pd.crosstab(churners.churn, churners.sexo, margins = True)

In [218]:
voter_tab

sexo        Femenino  Masculino   All
churn                                
Actual           250        582   832
Voluntario       423         90   513
All              673        672  1345

In [134]:
n = len(voter_tab)
n

3

In [219]:
sex_churn=voter_tab.iloc[0:(n-1)].drop('All',axis=1).values
sex_churn

array([[250, 582],
       [423,  90],
       [673, 672]], dtype=int64)

In [220]:
stats.chi2_contingency(sex_churn)

(348.63811319474377,
 1.968772929345335e-76,
 2,
 array([[ 416.30929368,  415.69070632],
        [ 256.69070632,  256.30929368],
        [ 673.        ,  672.        ]]))

El primer valor es el valor chi cuadrado. 

El segundo valor es el p_valor.

El tercer valor son los grados de libertad.

El cuarto valor la tabla de contigencia con los valores esperados.

### Churn vs.Estado Civil

In [222]:
a=churners_data['CHURN']
b=churners_data['CIVIL']
churners = pd.DataFrame({"churn":a, 
                       "civil":b})


voter_tab = pd.crosstab(churners.churn, churners.civil, margins = True)

In [223]:
voter_tab

civil       Casado  Soltero   All
churn                            
Actual         494      338   832
Voluntario     306      207   513
All            800      545  1345

In [224]:
n=len(voter_tab)
civil_churn=voter_tab.iloc[0:(n-1)].drop('All',axis=1).values
civil_churn

array([[494, 338],
       [306, 207]], dtype=int64)

In [226]:
stats.chi2_contingency(civil_churn)

(0.0017888802686799174,
 0.96626340633593033,
 1,
 array([[ 494.86988848,  337.13011152],
        [ 305.13011152,  207.86988848]]))

# ANOVA

In [139]:
churners_data_0.head()

ID  EDAD       SEXO    CIVIL  HIJOS   INGRESO                    AUTO  \
0   0    57   Femenino   Casado      2  27535.30     Es dueño de un auto   
1   4    68   Femenino   Casado      2  81000.90  No es dueño de un auto   
3  10    60  Masculino   Casado      2  83220.60  No es dueño de un auto   
4  13    28   Femenino   Casado      2  20850.40  No es dueño de un auto   
6  19    87   Femenino  Soltero      2   3776.12  No es dueño de un auto   

        CHURN  
0  Voluntario  
1  Voluntario  
3  Voluntario  
4  Voluntario  
6  Voluntario

In [227]:
churners_d1=churners_data_0[['CIVIL','INGRESO']]

In [228]:
churners_d1.groupby(['CIVIL'])['CIVIL'].count()

CIVIL
Casado     306
Soltero    207
Name: CIVIL, dtype: int64

In [229]:
churners_casado=churners_d1[churners_d1['CIVIL']=='Casado']
churners_casado.head()

CIVIL  INGRESO
0  Casado  27535.3
1  Casado  81000.9
3  Casado  83220.6
4  Casado  20850.4
7  Casado  73865.9

In [230]:
ch_casados=churners_casado.iloc[:,1].values
ch_casados

array([ 27535.3  ,  81000.9  ,  83220.6  ,  20850.4  ,  73865.9  ,
        12309.6  ,  13774.2  ,  23564.1  ,  87251.8  ,   2974.76 ,
        27842.1  ,   9925.68 ,  37155.   ,  38950.5  ,  18913.2  ,
        99398.1  ,  46734.5  ,  22767.   ,  77622.9  ,  41416.8  ,
        27376.   ,  24943.   ,  79771.3  ,  18199.7  ,  56816.4  ,
        50290.7  ,  63314.6  ,  42877.2  ,  18672.   ,  21126.7  ,
        81576.2  ,  82051.9  ,  39516.3  ,  48334.1  ,  17964.   ,
        15980.1  ,  21380.9  ,  85205.1  ,  50613.1  ,  65619.8  ,
        95394.   ,  49188.9  ,  83165.7  ,  80667.4  ,  10250.1  ,
        83039.2  ,  63306.6  ,  34317.6  ,  99248.1  ,   8749.8  ,
        11434.6  ,  54430.2  ,   7071.46 ,  97318.6  ,  57611.4  ,
          295.941,  27667.6  ,   7673.47 ,  99832.9  ,  54039.4  ,
        17755.4  ,   4581.11 ,  63328.8  ,  62685.   ,  51014.   ,
        18552.7  ,  50290.7  ,  37389.2  ,   5936.48 ,  42846.2  ,
        38705.5  ,  58345.8  ,  25445.6  ,   1846.01 ,  95847.

In [231]:
churners_solteros=churners_d1[churners_d1['CIVIL']=='Soltero']
churners_solteros.head()

CIVIL   INGRESO
6   Soltero   3776.12
10  Soltero  69864.00
17  Soltero  85753.80
29  Soltero   8383.47
31  Soltero  88413.40

In [232]:
ch_solteros=churners_solteros.iloc[:,1].values
ch_solteros

array([  3776.12,  69864.  ,  85753.8 ,   8383.47,  88413.4 ,  81420.  ,
        44143.1 ,  69454.6 ,  63769.7 ,  96112.1 ,  49776.2 ,   4335.86,
        74912.1 ,   9431.04,  50290.7 ,  88990.6 ,  14740.1 ,  77293.  ,
        48262.4 ,  79727.  ,  24896.1 ,  50050.5 ,  78854.9 ,  83977.6 ,
        95489.4 ,  35235.9 ,  50290.7 ,  61231.7 ,  80066.3 ,  61205.6 ,
        37809.7 ,  15434.3 ,  79133.  ,  91646.6 ,  42002.  ,  21395.2 ,
        72800.9 ,  98860.1 ,  47396.2 ,  41624.7 ,  23892.2 ,  34160.5 ,
        31639.2 ,  46771.2 ,  17689.2 ,  45310.4 ,  31809.7 ,  14082.  ,
        39700.3 ,  60310.6 ,  62275.3 ,  95056.9 ,  55050.5 ,  48506.7 ,
        54486.5 ,  57952.6 ,  19998.4 ,  43151.7 ,  17491.4 ,  10764.6 ,
        21529.1 ,  48271.8 ,  77021.7 ,  48841.4 ,  14905.  ,  11503.8 ,
        13094.8 ,  17540.7 ,  71906.8 ,  50290.7 ,  12686.9 ,  76845.3 ,
        58384.3 ,  57322.1 ,   7737.94,  57904.4 ,   4972.89,  92187.1 ,
        85774.3 ,   2638.11,  30234.8 ,  13965.4 , 

In [233]:
stats.f_oneway(ch_casados,ch_solteros)

F_onewayResult(statistic=0.017814394459747213, pvalue=0.89387377927474354)

El primer valor nos da el estadístico de prueba (F) y el segundo valor es el pvalor de la prueba